### ISSUE TITLE
Colorize text (and custom icons)

### ISSUE THREAD

**Issue by Tanjamuse** [juanjoarranz/style-text-obsidian-plugin#2]
Hello.

A) thank you for an amazing plugin, I was just about to ask for a css code that would let me do exactly what your plugin can.

B) have you considered an option that lets the user colorize the text and not the background? (and would work with custom emojis like in the icon shortcuts plugin)

**Comment by DudeThatsErin** [comment]
Idk about this part "(and would work with custom emojis like in the icon shortcuts plugin)" BUT the first part of B works. I can see it working in the image... `color: red` is coloring the text.

**Comment by Tanjamuse** [comment]
Yes *facepalms* I did notice that just moments before I got your reply here.
